
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDELLLAVE RLLAVE EQUALS COMMA NUMBER ARROBA PLUS MINUS TIMES DIVIDE STRING ARTICULO AUTOR TITLE YEAR PAGE NOTE VOLUMEN JOURNAL NUMERO MONTH PUBLISHER SERIES ADDRESS ISBN BOOKTITLE EDITOR ONGANIZATION BOOK EDITION CONFERENCE MANUAL UNPUBLISHEDstatement : titulo\n                    | autor\n                    | unpublished\n                    | nota\n                    | mes\n                    | aniostatement : STRINGanio : YEAR EQUALS NUMBERstatement : ARROBA UNPUBLISHEDtitulo : TITLE EQUALS LLLAVE STRING RLLAVEautor : AUTOR EQUALS LLLAVE STRING RLLAVEnota : NOTE EQUALS LLLAVE STRING RLLAVEmes : MONTH EQUALS NUMBERstatement : ARROBA UNPUBLISHED LLLAVE STRING COMMAexpression : NUMBERunpublished : ARROBA UNPUBLISHED LLLAVE STRING COMMA autor COMMA titulo COMMA nota COMMA mes COMMA anio RLLAVEexpression : expression PLUS expression\n                      | expression MINUS expression\n                      | expression TIMES expression\n                      | expression DIVIDE expression'
    
_lr_action_items = {'STRING':([0,21,22,23,24,],[8,27,28,29,30,]),'ARROBA':([0,],[9,]),'TITLE':([0,36,],[10,10,]),'AUTOR':([0,31,],[11,11,]),'NOTE':([0,38,],[12,12,]),'MONTH':([0,40,],[13,13,]),'YEAR':([0,42,],[14,14,]),'$end':([1,2,3,4,5,6,7,8,15,25,26,31,32,33,34,44,],[0,-1,-2,-3,-4,-5,-6,-7,-9,-13,-8,-14,-10,-11,-12,-16,]),'UNPUBLISHED':([9,],[15,]),'EQUALS':([10,11,12,13,14,],[16,17,18,19,20,]),'LLLAVE':([15,16,17,18,],[21,22,23,24,]),'NUMBER':([19,20,],[25,26,]),'COMMA':([25,27,32,33,34,35,37,39,41,],[-13,31,-10,-11,-12,36,38,40,42,]),'RLLAVE':([26,28,29,30,43,],[-8,32,33,34,44,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'titulo':([0,36,],[2,37,]),'autor':([0,31,],[3,35,]),'unpublished':([0,],[4,]),'nota':([0,38,],[5,39,]),'mes':([0,40,],[6,41,]),'anio':([0,42,],[7,43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> titulo','statement',1,'p_statement_reservadas','A_Sintactico_publicacion_Bibtext.py',14),
  ('statement -> autor','statement',1,'p_statement_reservadas','A_Sintactico_publicacion_Bibtext.py',15),
  ('statement -> unpublished','statement',1,'p_statement_reservadas','A_Sintactico_publicacion_Bibtext.py',16),
  ('statement -> nota','statement',1,'p_statement_reservadas','A_Sintactico_publicacion_Bibtext.py',17),
  ('statement -> mes','statement',1,'p_statement_reservadas','A_Sintactico_publicacion_Bibtext.py',18),
  ('statement -> anio','statement',1,'p_statement_reservadas','A_Sintactico_publicacion_Bibtext.py',19),
  ('statement -> STRING','statement',1,'p_statement_bloque','A_Sintactico_publicacion_Bibtext.py',23),
  ('anio -> YEAR EQUALS NUMBER','anio',3,'p_statement_year_assing','A_Sintactico_publicacion_Bibtext.py',28),
  ('statement -> ARROBA UNPUBLISHED','statement',2,'p_statement_arroba_assign','A_Sintactico_publicacion_Bibtext.py',33),
  ('titulo -> TITLE EQUALS LLLAVE STRING RLLAVE','titulo',5,'p_statement_title_assign','A_Sintactico_publicacion_Bibtext.py',38),
  ('autor -> AUTOR EQUALS LLLAVE STRING RLLAVE','autor',5,'p_statement_autor_assign','A_Sintactico_publicacion_Bibtext.py',43),
  ('nota -> NOTE EQUALS LLLAVE STRING RLLAVE','nota',5,'p_statement_note_assign','A_Sintactico_publicacion_Bibtext.py',48),
  ('mes -> MONTH EQUALS NUMBER','mes',3,'p_statement_mes_assign','A_Sintactico_publicacion_Bibtext.py',53),
  ('statement -> ARROBA UNPUBLISHED LLLAVE STRING COMMA','statement',5,'p_expression_name','A_Sintactico_publicacion_Bibtext.py',58),
  ('expression -> NUMBER','expression',1,'p_expression_number','A_Sintactico_publicacion_Bibtext.py',63),
  ('unpublished -> ARROBA UNPUBLISHED LLLAVE STRING COMMA autor COMMA titulo COMMA nota COMMA mes COMMA anio RLLAVE','unpublished',15,'p_estructura','A_Sintactico_publicacion_Bibtext.py',67),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','A_Sintactico_publicacion_Bibtext.py',72),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','A_Sintactico_publicacion_Bibtext.py',73),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','A_Sintactico_publicacion_Bibtext.py',74),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','A_Sintactico_publicacion_Bibtext.py',75),
]
